name: grenbot
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - openssl=1.1.1q
  - pip=21.0.1
  - python=3.9.5
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tzdata=2022a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==20.3.0
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - chardet==3.0.4
    - discord-py==2.0.0
    - et-xmlfile==1.1.0
    - idna==2.10
    - idna-ssl==1.1.0
    - multidict==5.1.0
    - numpy==1.23.5
    - openpyxl==3.0.10
    - pandas==1.5.1
    - python-dateutil==2.8.2
    - python-dotenv==0.15.0
    - pytz==2022.6
    - requests==2.23.0
    - six==1.16.0
    - soupsieve==2.3.1
    - typing-extensions==3.10.0.0
    - urllib3==1.25.11
    - yarl==1.6.3
